// Character roster — Tekken / DBFZ inspired fighters.
// 24 unique fighters, each with their own stats, fighting style and beam colors.

export interface Fighter {
  id: string;
  name: string;
  title: string;
  emoji: string;
  color: string;      // primary body color
  accent: string;     // accent / aura color
  speed: number;      // movement multiplier
  power: number;      // damage multiplier
  health: number;     // base HP
  jump: number;       // jump strength
  special: string;    // special move name
  specialColor: string; // main beam color (unique per fighter)
  beamCore?: string;  // inner white-hot core tint
  beamGlow?: string;  // outer blurred aura color
  style: string;      // fighting style description
}

export const FIGHTERS: Fighter[] = [
  {
    id: "blaze",
    name: "BLAZE",
    title: "The Inferno King",
    emoji: "🔥",
    color: "#ff5b3b",
    accent: "#ffd23b",
    speed: 1.05, power: 1.1, health: 100, jump: 1.0,
    special: "DRAGON FLAME",
    specialColor: "#ff6a00", beamCore: "#fff3c0", beamGlow: "#ff2a00",
    style: "Aggressive Striker",
  },
  {
    id: "frost",
    name: "FROST",
    title: "Ice Sovereign",
    emoji: "❄️",
    color: "#3bd0ff",
    accent: "#e0fbff",
    speed: 1.0, power: 1.05, health: 105, jump: 1.05,
    special: "GLACIER WAVE",
    specialColor: "#36c6ff", beamCore: "#eafdff", beamGlow: "#0a6cff",
    style: "Zoner / Control",
  },
  {
    id: "volt",
    name: "VOLT",
    title: "Thunder Fist",
    emoji: "⚡",
    color: "#ffe23b",
    accent: "#fff7c2",
    speed: 1.2, power: 0.95, health: 90, jump: 1.15,
    special: "LIGHTNING RUSH",
    specialColor: "#ffe600", beamCore: "#ffffff", beamGlow: "#ff9d00",
    style: "Speed Rushdown",
  },
  {
    id: "venom",
    name: "VENOM",
    title: "Shadow Assassin",
    emoji: "🐍",
    color: "#8a3bff",
    accent: "#3bff8a",
    speed: 1.1, power: 1.0, health: 95, jump: 1.1,
    special: "TOXIC STRIKE",
    specialColor: "#56ff5b", beamCore: "#e8ffe0", beamGlow: "#8a00ff",
    style: "Mix-up Master",
  },
  {
    id: "titan",
    name: "TITAN",
    title: "The Unbreakable",
    emoji: "🛡️",
    color: "#9aa3b2",
    accent: "#ffce3b",
    speed: 0.82, power: 1.3, health: 130, jump: 0.85,
    special: "EARTHQUAKE SLAM",
    specialColor: "#e0a23b", beamCore: "#fff0c0", beamGlow: "#8a4a00",
    style: "Heavy Grappler",
  },
  {
    id: "nova",
    name: "NOVA",
    title: "Cosmic Warrior",
    emoji: "🌟",
    color: "#ff3bd0",
    accent: "#8a3bff",
    speed: 1.08, power: 1.08, health: 100, jump: 1.1,
    special: "SUPERNOVA BEAM",
    specialColor: "#ff3bd0", beamCore: "#ffffff", beamGlow: "#6a00ff",
    style: "All-Rounder",
  },
  {
    id: "ronin",
    name: "RONIN",
    title: "Blade Master",
    emoji: "⚔️",
    color: "#3bffb0",
    accent: "#ffffff",
    speed: 1.12, power: 1.12, health: 92, jump: 1.05,
    special: "THOUSAND CUTS",
    specialColor: "#3bffd0", beamCore: "#ffffff", beamGlow: "#00b89e",
    style: "Precision Slasher",
  },
  {
    id: "magma",
    name: "MAGMA",
    title: "Volcanic Beast",
    emoji: "🌋",
    color: "#ff8c3b",
    accent: "#ff3b3b",
    speed: 0.95, power: 1.2, health: 115, jump: 0.95,
    special: "ERUPTION",
    specialColor: "#ff3b00", beamCore: "#ffe08a", beamGlow: "#b80000",
    style: "Power Bruiser",
  },
  {
    id: "tempest",
    name: "TEMPEST",
    title: "Storm Caller",
    emoji: "🌪️",
    color: "#5bc8d6",
    accent: "#d6f5ff",
    speed: 1.15, power: 1.0, health: 96, jump: 1.2,
    special: "CYCLONE BLAST",
    specialColor: "#7fffd4", beamCore: "#ffffff", beamGlow: "#2a8fb0",
    style: "Aerial Tornado",
  },
  {
    id: "obsidian",
    name: "OBSIDIAN",
    title: "Dark Monolith",
    emoji: "🖤",
    color: "#3a3a4a",
    accent: "#a05bff",
    speed: 0.9, power: 1.25, health: 120, jump: 0.9,
    special: "VOID CRUSHER",
    specialColor: "#a05bff", beamCore: "#e0c0ff", beamGlow: "#2a004a",
    style: "Defensive Tank",
  },
  {
    id: "seraph",
    name: "SERAPH",
    title: "Holy Avenger",
    emoji: "👼",
    color: "#fff0c0",
    accent: "#ffd23b",
    speed: 1.05, power: 1.1, health: 102, jump: 1.15,
    special: "DIVINE LIGHT",
    specialColor: "#fff6c0", beamCore: "#ffffff", beamGlow: "#ffae00",
    style: "Holy Zoner",
  },
  {
    id: "reaper",
    name: "REAPER",
    title: "Soul Harvester",
    emoji: "💀",
    color: "#4a4a5a",
    accent: "#56ff5b",
    speed: 1.1, power: 1.15, health: 94, jump: 1.05,
    special: "SOUL SCYTHE",
    specialColor: "#56ff8a", beamCore: "#e0ffe0", beamGlow: "#1a4a1a",
    style: "Lethal Hunter",
  },
  {
    id: "aqua",
    name: "AQUA",
    title: "Tide Empress",
    emoji: "🌊",
    color: "#3b8aff",
    accent: "#8ad0ff",
    speed: 1.06, power: 1.02, health: 100, jump: 1.08,
    special: "TSUNAMI SURGE",
    specialColor: "#3b9bff", beamCore: "#dfffff", beamGlow: "#0040b0",
    style: "Flow Fighter",
  },
  {
    id: "phantom",
    name: "PHANTOM",
    title: "Ghost Walker",
    emoji: "👻",
    color: "#c0c0e0",
    accent: "#8a8aff",
    speed: 1.25, power: 0.92, health: 88, jump: 1.2,
    special: "SPECTRAL DASH",
    specialColor: "#b0b0ff", beamCore: "#ffffff", beamGlow: "#5050c0",
    style: "Evasive Trickster",
  },
  {
    id: "inferna",
    name: "INFERNA",
    title: "Flame Empress",
    emoji: "💃",
    color: "#ff3b6a",
    accent: "#ffb03b",
    speed: 1.14, power: 1.06, health: 95, jump: 1.1,
    special: "PHOENIX KISS",
    specialColor: "#ff5b6a", beamCore: "#fff0c0", beamGlow: "#b8003b",
    style: "Combo Dancer",
  },
  {
    id: "goliath",
    name: "GOLIATH",
    title: "Mountain Crusher",
    emoji: "🦏",
    color: "#7a6a5a",
    accent: "#ffce3b",
    speed: 0.75, power: 1.4, health: 145, jump: 0.8,
    special: "BOULDER SMASH",
    specialColor: "#d68a3b", beamCore: "#fff0c0", beamGlow: "#5a3a00",
    style: "Super Heavyweight",
  },
  {
    id: "spark",
    name: "SPARK",
    title: "Neon Speedster",
    emoji: "🛹",
    color: "#3bffea",
    accent: "#ff3bd0",
    speed: 1.3, power: 0.88, health: 85, jump: 1.25,
    special: "PLASMA SLIDE",
    specialColor: "#3bffea", beamCore: "#ffffff", beamGlow: "#ff3bd0",
    style: "Hyper Rushdown",
  },
  {
    id: "kaiju",
    name: "KAIJU",
    title: "Beast of Ruin",
    emoji: "🦖",
    color: "#5aaa4a",
    accent: "#ffce3b",
    speed: 0.9, power: 1.28, health: 122, jump: 0.95,
    special: "ATOMIC ROAR",
    specialColor: "#9bff3b", beamCore: "#eaffd0", beamGlow: "#2a6a00",
    style: "Monster Bruiser",
  },
  {
    id: "mystic",
    name: "MYSTIC",
    title: "Arcane Sage",
    emoji: "🔮",
    color: "#8a5bff",
    accent: "#ff8aff",
    speed: 1.02, power: 1.12, health: 98, jump: 1.05,
    special: "ARCANE ORB",
    specialColor: "#c08aff", beamCore: "#ffffff", beamGlow: "#5a00aa",
    style: "Spell Caster",
  },
  {
    id: "blade",
    name: "BLADE",
    title: "Steel Reaver",
    emoji: "🗡️",
    color: "#aab0c0",
    accent: "#ff3b3b",
    speed: 1.16, power: 1.14, health: 90, jump: 1.08,
    special: "CRIMSON SLASH",
    specialColor: "#ff3b5b", beamCore: "#ffffff", beamGlow: "#8a0000",
    style: "Aggressive Duelist",
  },
  {
    id: "lumen",
    name: "LUMEN",
    title: "Prism Knight",
    emoji: "🌈",
    color: "#ff8ad0",
    accent: "#8affd0",
    speed: 1.08, power: 1.08, health: 100, jump: 1.12,
    special: "RAINBOW RAY",
    specialColor: "#8affd0", beamCore: "#ffffff", beamGlow: "#ff8ad0",
    style: "Spectrum Mixer",
  },
  {
    id: "drakon",
    name: "DRAKON",
    title: "Dragon Lord",
    emoji: "🐲",
    color: "#3baa6a",
    accent: "#ffce3b",
    speed: 1.0, power: 1.22, health: 112, jump: 1.0,
    special: "DRAGON BREATH",
    specialColor: "#3bffae", beamCore: "#fff0c0", beamGlow: "#0a6a3a",
    style: "Balanced Powerhouse",
  },
  {
    id: "celesta",
    name: "CELESTA",
    title: "Star Maiden",
    emoji: "✨",
    color: "#ffd23b",
    accent: "#8a5bff",
    speed: 1.12, power: 1.05, health: 96, jump: 1.18,
    special: "METEOR SHOWER",
    specialColor: "#ffd23b", beamCore: "#ffffff", beamGlow: "#8a5bff",
    style: "Cosmic Trapper",
  },
  {
    id: "ragnar",
    name: "RAGNAR",
    title: "Viking Berserker",
    emoji: "🪓",
    color: "#c08a5a",
    accent: "#ff3b3b",
    speed: 0.96, power: 1.26, health: 118, jump: 0.95,
    special: "BERSERK AXE",
    specialColor: "#ff7b3b", beamCore: "#fff0c0", beamGlow: "#8a2a00",
    style: "Rage Bruiser",
  },
];

export function getFighter(id: string): Fighter {
  return FIGHTERS.find((f) => f.id === id) || FIGHTERS[0];
}
